version: '3'

services:

  mainserver:
    build: ./main
    depends_on:
      - mongodbdatabase
    container_name: storageMainServer
    ports:
      - 82:8080
    volumes:
      
      - ./main:/usr/src/app/main
      - ./main/node_modules:/usr/src/app/main/node_modules

  mongodbdatabase:
    image: mongo
    container_name: storageMongoDB
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: toor
      MONGO_INITDB_ROOT_PASSWORD: root
